### PR TITLE
Separated TimeZone core logic from the webservice

### PR DESCRIPTION
**Pull request by jguthrie100**
I've created a new class to store the core logic (TimeZoneReader) and separated the logic from the webservice so I can have a crack at writing a solution for https://github.com/graphhopper/graphhopper/issues/1259

### CODE REVIEW

**Comment by jguthrie100** [comment]
HOWEVER: I have not compiled the new Jar files or touched anything to do with the Maven files.

I really have no experience working with Maven and would be happier if someone else took charge of that bit if possible? (Or explained to me how to do it properly in Eclipse..)

**Comment by karussell** [comment]
Thanks a lot!

> Or explained to me how to do it properly in Eclipse

You can always verify if the settings work via command line and finally here at github via travis. See [this build which is green](https://travis-ci.org/graphhopper/timezone/builds/342905479) and is about your current changes. Creating maven sub modules should not be that hard as you create a parent pom linking to all sub modules like `core` and `web` and the submodules link back to the parent inside the pom.xml. See e.g. [here](https://github.com/graphhopper/graphhopper/blob/master/pom.xml#L75) and [here](https://github.com/graphhopper/graphhopper/blob/master/core/pom.xml#L15-L19). (Please keep the version at 1.0-SNAPSHOT)

**Comment by jguthrie100** [comment]
I'm having trouble getting the POM configuration to create a basic .jar file after splitting the project into submodules, as explained on this SO post.. https://stackoverflow.com/questions/21021485/how-to-configure-maven-shade-plugin-in-a-multi-module-project

Is what I've uploaded ok (which creates a timezone-release module as suggested in the SO post), or should I just revert it back to being a single module??

**Comment by oblonski** [comment]
Thanks for your contribution. Would you mind to revert it to the single module? I can setup the modules.

**Comment by oblonski** [comment]
Would you mind to send us an email (https://www.graphhopper.com/imprint/) so that we can send you a CLA? Thanks.

**Comment by jguthrie100** [comment]
@oblonski - No problem, I've reverted it back! :+1:

**Pull request merged**
